//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss.Web.Utils.ajaxmin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JScript() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.Web.Utils.ajaxmin.JavaScript.JScript", typeof(JScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Ambiguous catch identifier. Cross-browser behavior difference.  的本地化字符串。
        /// </summary>
        internal static string AmbiguousCatchVar {
            get {
                return ResourceManager.GetString("AmbiguousCatchVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ambiguous reference to named function expression. Cross-browser behavior difference 的本地化字符串。
        /// </summary>
        internal static string AmbiguousNamedFunctionExpression {
            get {
                return ResourceManager.GetString("AmbiguousNamedFunctionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application failed. Please report this issue. 的本地化字符串。
        /// </summary>
        internal static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument defined but not referenced 的本地化字符串。
        /// </summary>
        internal static string ArgumentNotReferenced {
            get {
                return ResourceManager.GetString("ArgumentNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assignment to constant 的本地化字符串。
        /// </summary>
        internal static string AssignmentToConstant {
            get {
                return ResourceManager.GetString("AssignmentToConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t have &apos;break&apos; outside of loop 的本地化字符串。
        /// </summary>
        internal static string BadBreak {
            get {
                return ResourceManager.GetString("BadBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t have &apos;continue&apos; outside of loop 的本地化字符串。
        /// </summary>
        internal static string BadContinue {
            get {
                return ResourceManager.GetString("BadContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid hexadecimal escape sequence 的本地化字符串。
        /// </summary>
        internal static string BadHexEscapeSequence {
            get {
                return ResourceManager.GetString("BadHexEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label redefined 的本地化字符串。
        /// </summary>
        internal static string BadLabel {
            get {
                return ResourceManager.GetString("BadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid numeric literal 的本地化字符串。
        /// </summary>
        internal static string BadNumericLiteral {
            get {
                return ResourceManager.GetString("BadNumericLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;return&apos; statement outside of function 的本地化字符串。
        /// </summary>
        internal static string BadReturn {
            get {
                return ResourceManager.GetString("BadReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing &apos;case&apos; or &apos;default&apos; statement 的本地化字符串。
        /// </summary>
        internal static string BadSwitch {
            get {
                return ResourceManager.GetString("BadSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmatched &apos;@else&apos;; no &apos;@if&apos; defined 的本地化字符串。
        /// </summary>
        internal static string CCInvalidElse {
            get {
                return ResourceManager.GetString("CCInvalidElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmatched &apos;@elif&apos;; no &apos;@if&apos; defined 的本地化字符串。
        /// </summary>
        internal static string CCInvalidElseIf {
            get {
                return ResourceManager.GetString("CCInvalidElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmatched &apos;@end&apos;; no &apos;@if&apos; defined 的本地化字符串。
        /// </summary>
        internal static string CCInvalidEnd {
            get {
                return ResourceManager.GetString("CCInvalidEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditional compilation is turned off 的本地化字符串。
        /// </summary>
        internal static string CCOff {
            get {
                return ResourceManager.GetString("CCOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditional compilation expression not supported. Comment ignored 的本地化字符串。
        /// </summary>
        internal static string ConditionalCompilationTooComplex {
            get {
                return ResourceManager.GetString("ConditionalCompilationTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;default&apos; can only appear once in a &apos;switch&apos; statement 的本地化字符串。
        /// </summary>
        internal static string DupDefault {
            get {
                return ResourceManager.GetString("DupDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable or function declaration redefines the catch error name 的本地化字符串。
        /// </summary>
        internal static string DuplicateCatch {
            get {
                return ResourceManager.GetString("DuplicateCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant declaration already declared 的本地化字符串。
        /// </summary>
        internal static string DuplicateConstantDeclaration {
            get {
                return ResourceManager.GetString("DuplicateConstantDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate lexical declaration; cannot redefine let or const variables 的本地化字符串。
        /// </summary>
        internal static string DuplicateLexicalDeclaration {
            get {
                return ResourceManager.GetString("DuplicateLexicalDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name is already defined 的本地化字符串。
        /// </summary>
        internal static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expecting more source characters 的本地化字符串。
        /// </summary>
        internal static string ErrorEndOfFile {
            get {
                return ResourceManager.GetString("ErrorEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected expression 的本地化字符串。
        /// </summary>
        internal static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fallback character encoding failed 的本地化字符串。
        /// </summary>
        internal static string FallbackEncodingFailed {
            get {
                return ResourceManager.GetString("FallbackEncodingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function expression expected 的本地化字符串。
        /// </summary>
        internal static string FunctionExpressionExpected {
            get {
                return ResourceManager.GetString("FunctionExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function name should be a simple identifier; possible browser-specific implementation 的本地化字符串。
        /// </summary>
        internal static string FunctionNameMustBeIdentifier {
            get {
                return ResourceManager.GetString("FunctionNameMustBeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function defined but not referenced 的本地化字符串。
        /// </summary>
        internal static string FunctionNotReferenced {
            get {
                return ResourceManager.GetString("FunctionNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal assignment 的本地化字符串。
        /// </summary>
        internal static string IllegalAssignment {
            get {
                return ResourceManager.GetString("IllegalAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid character 的本地化字符串。
        /// </summary>
        internal static string IllegalChar {
            get {
                return ResourceManager.GetString("IllegalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ***INTERNAL COMPILER ERROR*** 的本地化字符串。
        /// </summary>
        internal static string InternalCompilerError {
            get {
                return ResourceManager.GetString("InternalCompilerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmatched &apos;else&apos;; no &apos;if&apos; defined 的本地化字符串。
        /// </summary>
        internal static string InvalidElse {
            get {
                return ResourceManager.GetString("InvalidElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid JSON JavaScript nodes encountered during output 的本地化字符串。
        /// </summary>
        internal static string InvalidJSONOutput {
            get {
                return ResourceManager.GetString("InvalidJSONOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSParser Exception 的本地化字符串。
        /// </summary>
        internal static string JSParserException {
            get {
                return ResourceManager.GetString("JSParserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved words and should not be used as an identifier; cross-browser differences 的本地化字符串。
        /// </summary>
        internal static string KeywordUsedAsIdentifier {
            get {
                return ResourceManager.GetString("KeywordUsedAsIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function declaration should not be inside a statement. Cross-browser behavior difference 的本地化字符串。
        /// </summary>
        internal static string MisplacedFunctionDeclaration {
            get {
                return ResourceManager.GetString("MisplacedFunctionDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;catch&apos; 的本地化字符串。
        /// </summary>
        internal static string NoCatch {
            get {
                return ResourceManager.GetString("NoCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;@end&apos; 的本地化字符串。
        /// </summary>
        internal static string NoCCEnd {
            get {
                return ResourceManager.GetString("NoCCEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;:&apos; 的本地化字符串。
        /// </summary>
        internal static string NoColon {
            get {
                return ResourceManager.GetString("NoColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;,&apos; 的本地化字符串。
        /// </summary>
        internal static string NoComma {
            get {
                return ResourceManager.GetString("NoComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;,&apos;. Write &apos;identifier : Type&apos; rather than &apos;Type identifier&apos; to declare a typed parameter 的本地化字符串。
        /// </summary>
        internal static string NoCommaOrTypeDefinitionError {
            get {
                return ResourceManager.GetString("NoCommaOrTypeDefinitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated comment 的本地化字符串。
        /// </summary>
        internal static string NoCommentEnd {
            get {
                return ResourceManager.GetString("NoCommentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected ///#ENDDEBUG directive 的本地化字符串。
        /// </summary>
        internal static string NoEndDebugDirective {
            get {
                return ResourceManager.GetString("NoEndDebugDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected ///#ENDIF directive 的本地化字符串。
        /// </summary>
        internal static string NoEndIfDirective {
            get {
                return ResourceManager.GetString("NoEndIfDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;=&apos; 的本地化字符串。
        /// </summary>
        internal static string NoEqual {
            get {
                return ResourceManager.GetString("NoEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected identifier 的本地化字符串。
        /// </summary>
        internal static string NoIdentifier {
            get {
                return ResourceManager.GetString("NoIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label not found 的本地化字符串。
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;{&apos; 的本地化字符串。
        /// </summary>
        internal static string NoLeftCurly {
            get {
                return ResourceManager.GetString("NoLeftCurly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;(&apos; 的本地化字符串。
        /// </summary>
        internal static string NoLeftParenthesis {
            get {
                return ResourceManager.GetString("NoLeftParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected identifier or string 的本地化字符串。
        /// </summary>
        internal static string NoMemberIdentifier {
            get {
                return ResourceManager.GetString("NoMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;]&apos; 的本地化字符串。
        /// </summary>
        internal static string NoRightBracket {
            get {
                return ResourceManager.GetString("NoRightBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;,&apos; or &apos;]&apos; 的本地化字符串。
        /// </summary>
        internal static string NoRightBracketOrComma {
            get {
                return ResourceManager.GetString("NoRightBracketOrComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;}&apos; 的本地化字符串。
        /// </summary>
        internal static string NoRightCurly {
            get {
                return ResourceManager.GetString("NoRightCurly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;)&apos; 的本地化字符串。
        /// </summary>
        internal static string NoRightParenthesis {
            get {
                return ResourceManager.GetString("NoRightParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;,&apos; or &apos;)&apos; 的本地化字符串。
        /// </summary>
        internal static string NoRightParenthesisOrComma {
            get {
                return ResourceManager.GetString("NoRightParenthesisOrComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;;&apos; 的本地化字符串。
        /// </summary>
        internal static string NoSemicolon {
            get {
                return ResourceManager.GetString("NoSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected &apos;while&apos; 的本地化字符串。
        /// </summary>
        internal static string NoWhile {
            get {
                return ResourceManager.GetString("NoWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consider replacing maximum numeric literal with Number.MAX_VALUE 的本地化字符串。
        /// </summary>
        internal static string NumericMaximum {
            get {
                return ResourceManager.GetString("NumericMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consider replacing minimum numeric literal with Number.MIN_VALUE 的本地化字符串。
        /// </summary>
        internal static string NumericMinimum {
            get {
                return ResourceManager.GetString("NumericMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeric literal evaluates to Number.POSITIVE_INFINITY or Number.NEGATIVE_INFINITY 的本地化字符串。
        /// </summary>
        internal static string NumericOverflow {
            get {
                return ResourceManager.GetString("NumericOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object constructor should take no arguments 的本地化字符串。
        /// </summary>
        internal static string ObjectConstructorTakesNoArguments {
            get {
                return ResourceManager.GetString("ObjectConstructorTakesNoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved word used as object literal property name; cross-browser issue. 的本地化字符串。
        /// </summary>
        internal static string ObjectLiteralKeyword {
            get {
                return ResourceManager.GetString("ObjectLiteralKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Octal literals are deprecated. Possible cross-browser behavior difference 的本地化字符串。
        /// </summary>
        internal static string OctalLiteralsDeprecated {
            get {
                return ResourceManager.GetString("OctalLiteralsDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A variable argument list must be the last argument 的本地化字符串。
        /// </summary>
        internal static string ParameterListNotLast {
            get {
                return ResourceManager.GetString("ParameterListNotLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntax error in regular expression 的本地化字符串。
        /// </summary>
        internal static string RegExpSyntax {
            get {
                return ResourceManager.GetString("RegExpSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource reference must be single constant argument 的本地化字符串。
        /// </summary>
        internal static string ResourceReferenceMustBeConstant {
            get {
                return ResourceManager.GetString("ResourceReferenceMustBeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Semicolon insertion rules applied 的本地化字符串。
        /// </summary>
        internal static string SemicolonInsertion {
            get {
                return ResourceManager.GetString("SemicolonInsertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 run-time 的本地化字符串。
        /// </summary>
        internal static string Severity0 {
            get {
                return ResourceManager.GetString("Severity0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 coding 的本地化字符串。
        /// </summary>
        internal static string Severity1 {
            get {
                return ResourceManager.GetString("Severity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 的本地化字符串。
        /// </summary>
        internal static string Severity2 {
            get {
                return ResourceManager.GetString("Severity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 performance 的本地化字符串。
        /// </summary>
        internal static string Severity3 {
            get {
                return ResourceManager.GetString("Severity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 improper technique 的本地化字符串。
        /// </summary>
        internal static string Severity4 {
            get {
                return ResourceManager.GetString("Severity4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unknown ({0}) 的本地化字符串。
        /// </summary>
        internal static string SeverityUnknown {
            get {
                return ResourceManager.GetString("SeverityUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always use full statement blocks 的本地化字符串。
        /// </summary>
        internal static string StatementBlockExpected {
            get {
                return ResourceManager.GetString("StatementBlockExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict operator always evaluates to true or false 的本地化字符串。
        /// </summary>
        internal static string StrictComparisonIsAlwaysTrueOrFalse {
            get {
                return ResourceManager.GetString("StrictComparisonIsAlwaysTrueOrFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow certain argument names 的本地化字符串。
        /// </summary>
        internal static string StrictModeArgumentName {
            get {
                return ResourceManager.GetString("StrictModeArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow duplicate argument names 的本地化字符串。
        /// </summary>
        internal static string StrictModeDuplicateArgument {
            get {
                return ResourceManager.GetString("StrictModeDuplicateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow duplicate property names 的本地化字符串。
        /// </summary>
        internal static string StrictModeDuplicateProperty {
            get {
                return ResourceManager.GetString("StrictModeDuplicateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow certain function names 的本地化字符串。
        /// </summary>
        internal static string StrictModeFunctionName {
            get {
                return ResourceManager.GetString("StrictModeFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow assignment to certain variables 的本地化字符串。
        /// </summary>
        internal static string StrictModeInvalidAssign {
            get {
                return ResourceManager.GetString("StrictModeInvalidAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow certain delete operands 的本地化字符串。
        /// </summary>
        internal static string StrictModeInvalidDelete {
            get {
                return ResourceManager.GetString("StrictModeInvalidDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow ++ or -- on certain objects 的本地化字符串。
        /// </summary>
        internal static string StrictModeInvalidPreOrPost {
            get {
                return ResourceManager.GetString("StrictModeInvalidPreOrPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow with-statements 的本地化字符串。
        /// </summary>
        internal static string StrictModeNoWith {
            get {
                return ResourceManager.GetString("StrictModeNoWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow assignment to undefined variables 的本地化字符串。
        /// </summary>
        internal static string StrictModeUndefinedVariable {
            get {
                return ResourceManager.GetString("StrictModeUndefinedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict-mode does not allow certain variable names 的本地化字符串。
        /// </summary>
        internal static string StrictModeVariableName {
            get {
                return ResourceManager.GetString("StrictModeVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String literal is not safe for inline 的本地化字符串。
        /// </summary>
        internal static string StringNotInlineSafe {
            get {
                return ResourceManager.GetString("StringNotInlineSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suspect assignment operator 的本地化字符串。
        /// </summary>
        internal static string SuspectAssignment {
            get {
                return ResourceManager.GetString("SuspectAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suspect equality comparison 的本地化字符串。
        /// </summary>
        internal static string SuspectEquality {
            get {
                return ResourceManager.GetString("SuspectEquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suspect semicolon 的本地化字符串。
        /// </summary>
        internal static string SuspectSemicolon {
            get {
                return ResourceManager.GetString("SuspectSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntax error 的本地化字符串。
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many errors. The file might not be a JavaScript file 的本地化字符串。
        /// </summary>
        internal static string TooManyTokensSkipped {
            get {
                return ResourceManager.GetString("TooManyTokensSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception thrown and not caught 的本地化字符串。
        /// </summary>
        internal static string UncaughtException {
            get {
                return ResourceManager.GetString("UncaughtException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End of file encountered before function is properly closed 的本地化字符串。
        /// </summary>
        internal static string UnclosedFunction {
            get {
                return ResourceManager.GetString("UnclosedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function has not been defined 的本地化字符串。
        /// </summary>
        internal static string UndeclaredFunction {
            get {
                return ResourceManager.GetString("UndeclaredFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable has not been declared 的本地化字符串。
        /// </summary>
        internal static string UndeclaredVariable {
            get {
                return ResourceManager.GetString("UndeclaredVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected &apos;;&apos; 的本地化字符串。
        /// </summary>
        internal static string UnexpectedSemicolon {
            get {
                return ResourceManager.GetString("UnexpectedSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated ASP.NET block 的本地化字符串。
        /// </summary>
        internal static string UnterminatedAspNetBlock {
            get {
                return ResourceManager.GetString("UnterminatedAspNetBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated string constant 的本地化字符串。
        /// </summary>
        internal static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable defined but not referenced 的本地化字符串。
        /// </summary>
        internal static string VariableDefinedNotReferenced {
            get {
                return ResourceManager.GetString("VariableDefinedNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;with&apos; statement not recommended 的本地化字符串。
        /// </summary>
        internal static string WithNotRecommended {
            get {
                return ResourceManager.GetString("WithNotRecommended", resourceCulture);
            }
        }
    }
}
