//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss.XmlTransform {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.XmlTransform.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; was found in more than one assembly 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_AmbiguousTypeMatch {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_AmbiguousTypeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform and Locator attributes must contain only a type name, or a type name followed by a list of attributes in parentheses. 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_BadAttributeValue {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_BadAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal syntax error 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_FatalTransformSyntaxError {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_FatalTransformSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import tag cannot have both a &apos;path&apos; and an &apos;assembly&apos; 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_ImportAttributeConflict {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_ImportAttributeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import tag must have a &apos;path&apos; or an &apos;assembly&apos; 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_ImportMissingAssembly {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_ImportMissingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import tag must have a &apos;namespace&apos; 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_ImportMissingNamespace {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_ImportMissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import tag does not support &apos;{0}&apos; attribute 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_ImportUnknownAttribute {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_ImportUnknownAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a type of {1} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_IncorrectBaseType {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_IncorrectBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No element in the source document matches &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_InsertBadXPath {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_InsertBadXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; does not evaluate to an element 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_InsertBadXPathResult {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_InsertBadXPathResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} requires an XPath argument 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_InsertMissingArgument {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_InsertMissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many arguments to {0} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_InsertTooManyArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_InsertTooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No attribute &apos;{0}&apos; exists for the Match Locator 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_MatchAttributeDoesNotExist {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_MatchAttributeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; must have a no-argument constructor to be instantiated by the transformation engine 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_NoValidConstructor {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_NoValidConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} requires exactly {1} arguments 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_RequiresExactArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_RequiresExactArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} requires at least {1} arguments 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_RequiresMinimumArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_RequiresMinimumArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many arguments for {0} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TooManyArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument &apos;{0}&apos; did not match any attributes 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformArgumentFoundNoAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformArgumentFoundNoAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executing {0} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformBeginExecutingMessage {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformBeginExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} does not expect arguments; ignoring 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformDoesNotExpectArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformDoesNotExpectArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done executing {0} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformEndExecutingMessage {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformEndExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error during {0} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformErrorExecutingMessage {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformErrorExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inserted &apos;{0}&apos; element 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageInsert {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No attributes found to remove 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageNoRemoveAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageNoRemoveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No attributes found to set 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageNoSetAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageNoSetAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed &apos;{0}&apos; element 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageRemove {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed &apos;{0}&apos; attribute 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageRemoveAttribute {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageRemoveAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed {0} attributes 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageRemoveAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageRemoveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaced &apos;{0}&apos; element 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageReplace {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set &apos;{0}&apos; attribute 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageSetAttribute {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageSetAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set {0} attributes 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageSetAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageSetAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (transform line {1}, {2}) 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformNameFormatLong {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformNameFormatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformNameFormatShort {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformNameFormatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No element in the source document matches &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformNoMatchingTargetNodes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformNoMatchingTargetNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not executing {0} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformNotExecutingMessage {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformNotExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple target elements, but the &apos;{0}&apos; Transform only applies to the first match 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformOnlyAppliesOnce {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformOnlyAppliesOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; did not find a match, because matching nodes in the source document were modified or removed by a previous transform 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformSourceMatchWasRemoved {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformSourceMatchWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applying to &apos;{0}&apos; element (source line {1}, {2}) 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformStatusApplyTarget {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformStatusApplyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applying to &apos;{0}&apos; element (no source line info) 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformStatusApplyTargetNoLineInfo {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformStatusApplyTargetNoLineInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 on {0} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformStatusXPath {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformStatusXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not resolve &apos;{0}&apos; as a type of {1} 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_UnknownTypeName {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_UnknownTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown tag &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string XMLTRANSFORMATION_UnknownXdtTag {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_UnknownXdtTag", resourceCulture);
            }
        }
    }
}
